### ISSUE TITLE
Trying to compile on Mac OS X 10.9

### ISSUE THREAD

**Issue by oskarlin** [kartverket/fyba#12]
```
autoreconf --force --install
```

works 

```
./configure
```

also works. but when doing make I get this error message:

```
INQTID.cpp:18:11: fatal error: 'sys/vfs.h' file not found
# include<sys/vfs.h>
          ^
1 error generated.
make[2]: *** [INQTID.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

Any ideas?
